# Указывает версию синтаксиса Docker Compose.
version: '3.7'

# Определяет список сервисов (контейнеров), которые будут запущены.
services:

  # Сервис MongoDB.
  mongodb:
    # Использует последний доступный образ MongoDB.
    image: mongo:latest
    # Имя контейнера.
    container_name: mongodb
    # Пробрасывает порт 27017 контейнера на порт 27017 хоста, позволяя доступ к MongoDB.
    ports:
      - "27017:27017"
    # Монтирует локальную директорию './data' в директорию '/data/db' контейнера для сохранения данных.
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # Пользователь-администратор MongoDB.
      - MONGO_INITDB_ROOT_PASSWORD=root # Пароль администратора MongoDB.

  # Сервис ZooKeeper.
  zookeeper:
    # Образ ZooKeeper от Confluent для совместимости с Kafka.
    image: confluentinc/cp-zookeeper:latest
    # Имя контейнера.
    container_name: zookeeper
    # Порт клиента ZooKeeper.
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    # Пробрасывание порта.
    ports:
      - "2181:2181"
    # Общая сеть для Kafka и ZooKeeper.
    networks:
      - kafka-net

  # Сервис Kafka.
  kafka:
    # Образ Kafka от Confluent.
    image: confluentinc/cp-kafka:latest
    # Хостнейм внутри сети.
    hostname: kafka
    # Имя контейнера.
    container_name: kafka
    # Проброс внешнего порта Kafka.
    ports:
      - "9092:9092"
      - "9093:9093" # Удалить после отладки
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093  # Слушатель для подключения извне.
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093  # Слушатель для внутреннего общения
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181  # Подключение к ZooKeeper.
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT  # Имя слушателя для внутреннего общения.
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 # Фактор репликации топика смещений. Лечит проблему 1 брокера https://stackoverflow.com/questions/49490835/kafka-server-offsets-topic-has-not-yet-been-created
    # Гарантирует запуск ZooKeeper до Kafka.
    depends_on:
      - zookeeper
    # Общая сеть для Kafka и ZooKeeper.
    networks:
      - kafka-net

  # Сервис Kafdrop для Kafka UI - удалить после отладки
  kafdrop:
    # Образ kafdrop от Obsidiandynamics.
    image: obsidiandynamics/kafdrop:latest
    # Имя контейнера.
    container_name: kafdrop
    # Проброс порта.
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092 # Подключение к брокеру Kafka.
    # Гарантирует запуск Kafka до kafdrop.
    depends_on:
      - kafka
    # Общая сеть для Kafka, ZooKeeper И Kafdrop.
    networks:
      - kafka-net

networks:
  # Сеть для взаимодействия сервисов.
  kafka-net:
    # Драйвер сети (подходит для локальных окружений).
    driver: bridge
